### PR TITLE
test: Use a dedicated repo for the test cases

### PR DESCRIPTION
**Pull request by dimitrisnl**
Change-type: minor
Signed-off-by: Dimitrios Lytras <dimitrios@balena.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
This is very strange. In Travis the tests pass, but in ResinCI they don't.

```
  -   integrations: null,
  +   integrations: Array [ … ],
```

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by dimitrisnl** [comment]
@nazrhom 	Btw I always have to manually restart one of the two travis tests. Is there a reason for this happening?

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@dimitrisnl it turns out that the getIntegrations check will always return `null` if the token that is running it does not have the equivalent of admin access to the scrutinizer-test repo.

**Pull request merged**
