### PR TITLE
dependencies: Upgrade @octokit/rest

### PR DESCRIPTION
**Pull request by dimitrisnl**
Update the deprecated parts and generate package.lock

Connects-to: #20
Change-type: minor
Signed-off-by: Dimitrios Lytras <dimitrios@balena.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
Travis fails with 

```
message: 'API rate limit exceeded for 35.193.7.13. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)',
```

checking to see if it's a bug with how we initialize the GH client.

**Comment by dimitrisnl** [comment]
@jviotti 	We should reconsider our tests cases

For example, the integrations test isn't depending on the reference commit. We have to always be reactive to these changes, otherwise, the Scrutinizer tests will fail with false positives.

```
  e2e › remote: versionist (8d26949be685c9427bc6c48893572a2d5b8fe974)
  /home/travis/build/balena-io-modules/scrutinizer/test/e2e.spec.js:50
   49:     }).then((data) => {                    
   50:       test.deepEqual(data, testCase.result)
   51:     })                                     
  Difference:
    {
      architecture: null,
      contributing: null,
      dependencies: Array [ … ],
      integrations: [
  -     'ResinCI/check-commits/commits',
  +     'Versionist',
  -     'ResinCI/check-files/license',
  +     'appveyor',
  -     'ResinCI/check-files/readme',
  +     'travis-ci',
  -     'ResinCI/store-github/store-github',
  +     'AutoMerges',
  -     'ResinCI/check-versionist/versionist',
  +     'Reviewers',
  -     'ResinCI/npm/store-npm',
      ],
      license: 'Apache-2.0',
      public: true,
    }
```

**Comment by jviotti** [comment]
@dimitrisnl That's a good point. I'm happy to record the commit the tests were made on and use that when querying the GitHub API if possible. Otherwise let me know and we can discuss another solution.

**Comment by dimitrisnl** [comment]
@jviotti 	What do you mean by recording, isn't this what we do right now?

Considering GH will respond with the active integrations at the time of the call any values we persist are prone to be outdated.

Wouldn't having a simple type checking test suffice?

**Comment by dimitrisnl** [comment]
This is extended to other plugins as well. # of commits, top contributors etc

The calls that except a `ref` param are limited.

**Comment by jviotti** [comment]
@dimitrisnl Right, but then we should make sure we test real things on real repos, otherwise its hard to prove that it really works. What about creating a test repo with various things on it, and then mark it as "archived" on GH, which will make it completely read-only on GitHub, and then we assert on that?

**Comment by dimitrisnl** [comment]
status: Do not merge. I'll follow Juan's suggestion and update the tests cases.

**Comment by dimitrisnl** [comment]
This is a bit weird. The tests fail because the array items are in different order...

```
     integrations: [
        'concourse-ci/electron',
        'ResinCI/store-github/store-github',
        'ResinCI/check-versionist/versionist',
  -     'ResinCI/check-files/readme',
  +     'ResinCI/check-commits/commits',
  -     'ResinCI/check-commits/commits',
  +     'ResinCI/check-files/readme',
        'ResinCI/check-files/license',
      ],
```

**Comment by dimitrisnl** [comment]
@resin-ci 	retest

**Comment by dimitrisnl** [comment]
@resin-ci 	retest

**Comment by dimitrisnl** [comment]
I've noticed that sometimes the `ResinCI/check-files/license` isn't present in the checks. Which causes the DeepEqual check to fail.

**Comment by dimitrisnl** [comment]
@resin-ci 	retest

**Comment by dimitrisnl** [comment]
@resin-ci 	retest

**Comment by dimitrisnl** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Pull request merged**
