### PR TITLE
cli: Add a CLI interface

### PR DESCRIPTION
**Pull request by brownjohnf**
Change-type: minor
Signed-off-by: Jack Brown <jack@resin.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
Should we add a README entry?

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by dimitrisnl** [comment]
@nazrhom 	Is this still relevant? Should we close it?

**Comment by dimitrisnl** [comment]
Rebased over master, will follow up with a Readme update in a moment

**Comment by dimitrisnl** [comment]
WIP - doing some more testing

**Pull request merged**
